### ISSUE TITLE
Explore CyVerse for TERRA REF Pipeline

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/openstack-terraform-nomad#9]

**Comment by julianpistorius** [comment]
Good progress made. See: [meeting-notes/2019-09-05_helping-sateesh-gantry-pipeline.md](https://github.com/az-digitalag/organization/blob/a458f012269540e0de54b512973b936547e2c1ec/meeting-notes/2019-09-05_helping-sateesh-gantry-pipeline.md)

I asked:

> Question: Once the containers are integrated into the DE, and the CWL description is done, will the Makeflow engine:
> 1. Call the DE API to run the workflow step, or
> 2. Submit the container step directly to the HTCondor cluster 

Nirav said:

> 1. Makeflow engine will call the json (or make) written workflow definition (not CWL as it does not speak CWL). This will include the location of container (docker/signularity hub or private)
> 2. You will submit workers (HPC, cloud) which will dial home to this makeflow engine and take task and perform the work (and update the status as the go along). You can arbitrarily add more workers and get scaling of tasks.
